# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            /var/log/andrey
tagline:          Andrey Yurovsky's blog
url:              http://yurovsky.github.io
paginate:         1
author:
  name:           Andrey Yurovsky
  email:          yurovsky@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
