title: "/var/log/andrey"
url:              http://yurovsky.github.io/
description: >- # this means to ignore newlines until "baseurl:"
  My blog about Linux systems programming, firmware, and cars.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yurovsky.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: yurovsky

# Build settings
markdown: kramdown
hilighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
