# Dependencies
markdown:         kramdown 
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            /var/log/andrey
tagline:          Andrey Yurovsky's blog
url:              http://yurovsky.github.io
baseurl:          /
paginate:         5
author:
  name:           Andrey Yurovsky
  email:          yurovsky@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
